import type { IndustryPageConfig } from './types'

// ── SHARED COMPARISON SECTIONS ───────────────────────────
const sharedSupportRows = [
  { icon:'☁️', feature:'AWS Cloud Hosting (NNC Infrastructure)', starter:'✓', growth:'✓', enterprise:'✓' },
  { icon:'🚀', feature:'Setup & Data Migration Included',         starter:'✓', growth:'✓', enterprise:'✓' },
  { icon:'🎓', feature:'Staff Training & Onboarding',            starter:'✓', growth:'✓', enterprise:'✓' },
  { icon:'🛟', feature:'Post-Launch Support Period',             starter:'30 days', growth:'60 days', enterprise:'90 days' },
  { icon:'⏱', feature:'Support Response Time',                  starter:'24 hrs',  growth:'8 hrs',   enterprise:'4 hrs'   },
  { icon:'👔', feature:'Dedicated Account Manager',              starter:'—',       growth:'—',        enterprise:'✓'       },
]

// ══════════════════════════════════════════════════════════
// HOSPITALITY
// ══════════════════════════════════════════════════════════
export const hospitalityData: IndustryPageConfig = {
  id: 'hospitality',
  metaTitle: "CoreOS Hospitality CRM — #1 Hotel Management Software India | NNC",
  metaDesc:  "India's most trusted hotel management CRM. Room bookings, guest profiles, GST invoicing, housekeeping & WhatsApp automation. 200+ hotels live. From ₹14,999/year.",
  h1:        ["India's #1 Hotel", "Management CRM", "for Growing Hotels."],
  h1Sub:     "Trusted by 200+ hotels, resorts & guest houses across India",
  heroBadge: "HOSPITALITY CRM — INDIA BUILT · AWS HOSTED",
  heroSub:   "CoreOS Hospitality CRM handles room bookings, guest profiles, housekeeping, GST invoicing, and WhatsApp automation — all in one dashboard. No server to manage. We host it on AWS. Starting ₹14,999/year.",
  urgencyText: "Now serving hotels across Bengaluru, Mysuru, Mumbai & Hyderabad",
  proofText:   "200+ hotel owners running on CoreOS CRM · ★★★★★ 4.9/5",
  sizeLabel:   "Number of Rooms",
  wins: [
    { industry:'🏨 Resort · Coorg', hotel:'Serenity Resorts', location:'📍 Coorg, Karnataka · 45 Rooms · Growth Plan',
      result:'Switched from manual Excel billing to CoreOS CRM. GST invoice generation went from 2 hours every night to 30 seconds. WhatsApp invoice delivery is now their guests favourite feature.',
      metrics:[{n:'2hrs',l:'Saved daily'},{n:'100%',l:'GST accuracy'},{n:'0',l:'Invoice errors'}], time:'6 working days' },
    { industry:'🏨 Hotel · Bengaluru', hotel:'Kapoor Palace Hotels', location:'📍 Bengaluru, Karnataka · 80 Rooms · Growth Plan',
      result:'Used the guest loyalty module to identify top 20 repeat guests. Ran one targeted WhatsApp offer and filled 3 weekends instantly. ROI achieved in month 2 of going live.',
      metrics:[{n:'3',l:'Weekends filled'},{n:'23%',l:'Revenue up'},{n:'Month 2',l:'ROI achieved'}], time:'7 working days' },
    { industry:'🏡 Guest House · Mysuru', hotel:'The Heritage Inn', location:'📍 Mysuru, Karnataka · 22 Rooms · Starter Plan',
      result:'Was managing bookings over WhatsApp groups. First week on CoreOS CRM — double bookings dropped to zero. Staff now handle check-ins in 90 seconds.',
      metrics:[{n:'0',l:'Double bookings'},{n:'3 hrs',l:'Saved daily'},{n:'90s',l:'Check-in time'}], time:'5 working days' },
  ],
  plans: [
    { id:'starter', name:'Starter', price:14999, users:'1 user', rooms:'Up to 30 rooms', period:'per year', popular:false,
      description:'For guest houses, B&Bs, and small hotels up to 30 rooms.',
      features:['Room booking & floor plan','Guest profiles & UHID','GST invoice generation','WhatsApp booking confirmation','1 staff user account','AWS hosted — NNC infrastructure','Setup & data migration included'],
      notIncluded:['Housekeeping module','Multi-property dashboard'],
      support:'30 days', response:'24 hrs', mobile:'None' },
    { id:'growth', name:'Growth', price:29999, users:'3 users', rooms:'Up to 100 rooms', period:'per year', popular:true,
      description:'For hotels with 30–100 rooms. Full feature suite and complete WhatsApp automation.',
      features:['Everything in Starter','Housekeeping task management','F&B and extra charges billing','Advanced revenue analytics','3 staff user accounts','Full WhatsApp automation','Guest loyalty points & tiers','60-day post-launch support'],
      notIncluded:['Multi-property dashboard'],
      support:'60 days', response:'8 hrs', mobile:'None' },
    { id:'enterprise', name:'Enterprise', price:59999, users:'7 users', rooms:'Multi-property', period:'per year', popular:false,
      description:'For hotel chains and multi-property groups. Multi-property dashboard and advanced analytics.',
      features:['Everything in Growth','Multi-property dashboard','7 staff user accounts','Custom KPI dashboards','Dedicated account manager','90-day priority support'],
      notIncluded:[],
      support:'90 days', response:'4 hrs', mobile:'None' },
  ],
  problems: [
    { icon:'📋', title:'Double Bookings & Room Chaos', body:'No single source of truth. Staff confirm bookings over phone without checking real-time status. Double-bookings happen. Guests walk away angry. Reviews suffer.' },
    { icon:'🧾', title:'GST Invoice Errors Every Night', body:'Manual Excel billing leads to wrong GST calculations, delayed invoices, and tax notices. Your accountant spends hours correcting what a CRM does in 30 seconds.' },
    { icon:'👤', title:'Zero Guest Intelligence', body:'You have no idea who your best guests are, how often they stay, or what they spend. You are running a hotel without knowing your own customers.' },
    { icon:'🧹', title:'Housekeeping Miscommunication', body:'Staff do not know which rooms need cleaning and when. Guests check in to unready rooms and write 1-star reviews that kill your booking rankings for months.' },
    { icon:'📊', title:'Blind Revenue Management', body:'You do not know your occupancy rate, RevPAR, or daily revenue until end of month. By then you have already missed the chance to fix it.' },
    { icon:'💬', title:'No Automated Guest Communication', body:'Every booking confirmation, check-in reminder, and invoice is sent manually by staff. Time wasted. Mistakes made. Guest experience wildly inconsistent.' },
  ],
  features: [
    { id:'booking', icon:'🛏', title:'Room Availability & Booking',
      desc:'Real-time interactive floor plan. Instant availability check. Walk-in, phone, and OTA bookings in one dashboard.',
      bullets:['Live floor plan — colour-coded per room status','Instant double-booking prevention','OTA, direct walk-in & phone booking tracking','WhatsApp booking confirmation automatically'] },
    { id:'guests', icon:'👤', title:'Guest Profile Management',
      desc:'Every guest gets a permanent UHID. Full stay history, total spend, loyalty points, and ID verification — all in one card.',
      bullets:['Auto-generated UHID for every guest','Complete stay history and lifetime spend','Loyalty points & tier management','Guest flagging for payment defaults'] },
    { id:'billing', icon:'🧾', title:'GST Billing & Invoicing',
      desc:'Fully automated GST calculation — 12% or 18% based on tariff. Itemised bills with F&B, laundry, minibar.',
      bullets:['Auto CGST + SGST + IGST split calculation','F&B, laundry & extra charge line items','Discount with manager approval workflow','GST-compliant PDF invoice via WhatsApp'] },
    { id:'housekeeping', icon:'🧹', title:'Housekeeping Management',
      desc:'Real-time housekeeping board. Assign tasks to staff. Auto-notify on checkout. Every room ready before guest arrives.',
      bullets:['Live room status — clean / dirty / inspect / ready','Staff task assignment with priority flagging','Auto-notification on guest checkout','Supervisor dashboard with completion %'] },
    { id:'analytics', icon:'📊', title:'Revenue Analytics Dashboard',
      desc:'Live revenue, occupancy rate, RevPAR, and booking source analytics — on one screen.',
      bullets:['Daily / weekly / monthly revenue charts','Occupancy % by room type','Top guests by total lifetime spend','Export reports to Excel & PDF in one click'] },
    { id:'whatsapp', icon:'📱', title:'WhatsApp & SMS Automation',
      desc:'Booking confirmations, reminders, invoice delivery, and review requests — all sent automatically.',
      bullets:['Auto booking confirmation on WhatsApp','Checkout reminder 2 hours before due time','GST invoice delivered via WhatsApp','Post-checkout review request'] },
  ],
  processSteps: [
    { title:'Pay & Book Your Slot', text:'Pay via Razorpay online. NNC team WhatsApps you within 2 hours to confirm your onboarding date.' },
    { title:'Discovery Call',       text:'30-minute call. We document room types, tariffs, GST structure, staff roles, and WhatsApp preferences.' },
    { title:'Setup & Data Migration', text:'CoreOS configured on AWS, guest records migrated, WhatsApp templates and GST settings set up.' },
    { title:'Go Live + Training',   text:'2-hour staff training session. We stay on call for 30–90 days post-launch.' },
  ],
  comparison: [
    { category:'Core Modules', rows:[
      { icon:'🛏', feature:'Room Availability & Floor Plan',              starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'📋', feature:'Booking Management (Walk-in, OTA, Phone)',    starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'👤', feature:'Guest Profiles & UHID System',               starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🧾', feature:'GST Invoice Generation (CGST/SGST/IGST)',     starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🧹', feature:'Housekeeping Task Management',               starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🍽', feature:'F&B / Laundry / Extra Charges Billing',      starter:'—', growth:'✓', enterprise:'✓' },
    ]},
    { category:'Users & Access', rows:[
      { icon:'👥', feature:'Staff User Accounts',          starter:'1 user',  growth:'3 users', enterprise:'7 users' },
      { icon:'🔑', feature:'Role-Based Access Control',    starter:'Basic',   growth:'Advanced', enterprise:'Custom' },
      { icon:'🏨', feature:'Multi-Property Dashboard',     starter:'—',       growth:'—',        enterprise:'✓' },
    ]},
    { category:'Automation & Communication', rows:[
      { icon:'📱', feature:'WhatsApp Booking Confirmation',                  starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💌', feature:'Invoice Delivery via WhatsApp & Email',          starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🔔', feature:'Auto Checkout Reminders & Review Requests',      starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🎁', feature:'Guest Loyalty Points & Tier Management',         starter:'—', growth:'✓', enterprise:'✓' },
    ]},
    { category:'Analytics & Reports', rows:[
      { icon:'📊', feature:'Revenue Dashboard (Daily/Weekly/Monthly)', starter:'Basic',    growth:'Advanced', enterprise:'Custom' },
      { icon:'📈', feature:'Occupancy Rate & RevPAR Tracking',         starter:'—',        growth:'✓',        enterprise:'✓' },
      { icon:'📤', feature:'Export Reports to Excel & PDF',            starter:'—',        growth:'✓',        enterprise:'✓' },
      { icon:'🎯', feature:'Custom KPI Dashboards',                    starter:'—',        growth:'—',        enterprise:'✓' },
    ]},
    { category:'Technology & Integrations', rows:[
      
      
      
    ]},
    { category:'Support & Onboarding', rows: sharedSupportRows },
  ],
  testimonials: [
    { text:'We went from WhatsApp chaos to a fully professional CRM in one week. Revenue tracking alone saved us 2 hours every single day.', initials:'RN', name:'Ramesh Nair', role:'Owner · The Heritage Inn, Mysuru' },
    { text:'GST invoicing used to take 2 hours every night. Now it is 30 seconds. The WhatsApp invoice feature is something our guests absolutely love.', initials:'PS', name:'Priya Subramaniam', role:'GM · Serenity Resorts, Coorg' },
    { text:'The loyalty module helped us identify our top 20 guests. One targeted offer filled 3 weekends instantly. ROI in the first 2 months.', initials:'AK', name:'Arjun Kapoor', role:'Director · Kapoor Palace Hotels, Bengaluru' },
  ],
  faqs: [
    { q:'Is this yearly or one-time?', a:'Yearly subscription covering software licence, AWS hosting, WhatsApp API, updates, and support. No separate setup fee — all included. Cancel at any renewal date.' },
    { q:'Where is my data stored?', a:'AWS Mumbai (ap-south-1) with Row-Level Security, AES-256 encryption, and daily automated backups. Your data is isolated from all other clients.' },
    { q:'How long does setup take?', a:'7 working days from the discovery call — configuration, data migration, WhatsApp templates, and staff training. We give you a fixed go-live date in writing.' },
    { q:'Do I need technical knowledge?', a:'Zero. We train your front desk, managers, and housekeeping staff. Training takes 2 hours. WhatsApp support for issues resolved within 4 hours.' },
    { q:'Can I migrate existing guest data?', a:'Yes — included in all plans. We migrate from Excel, Google Sheets, or your existing hotel software at no extra charge.' },
    { q:'What is your refund policy?', a:'If we do not deliver within the promised 7-day go-live, you get a full refund — no questions asked. Cancel at any annual renewal date.' },
  ],
  finalH2: "Your Hotel Deserves Better than WhatsApp Groups & Excel.",
  finalP:  "Join 200+ hotels already running on CoreOS CRM. Setup in 7 days. Hosted on AWS. Full refund if we miss the deadline.",
}

// ══════════════════════════════════════════════════════════
// HEALTHCARE
// ══════════════════════════════════════════════════════════
export const healthcareData: IndustryPageConfig = {
  id: 'healthcare',
  metaTitle: "CoreOS Healthcare CRM — Clinic & Hospital Management Software India | NNC",
  metaDesc:  "Complete healthcare CRM for clinics, hospitals, and diagnostic centres. Patient registration, EMR, GST billing, WhatsApp automation. From ₹19,999/year.",
  h1:        ["India's #1 Clinic", "Management CRM", "for Growing Practices."],
  h1Sub:     "Trusted by 300+ clinics, hospitals & diagnostic centres across India",
  heroBadge: "HEALTHCARE CRM — INDIA BUILT · HIPAA-ALIGNED",
  heroSub:   "CoreOS Healthcare CRM handles patient registration, appointment scheduling, EMR, prescription writing, lab results, and GST billing — all in one HIPAA-aligned dashboard. AWS hosted. From ₹19,999/year.",
  urgencyText: "Now serving clinics & hospitals across Bengaluru, Mysuru, Mumbai & Hyderabad",
  proofText:   "300+ clinics running on CoreOS CRM · ★★★★★ 4.9/5",
  sizeLabel:   "Number of Doctors",
  wins: [
    { industry:'🏥 Cardiology · Bengaluru', hotel:'Iyer Heart Clinic', location:'📍 Bengaluru, Karnataka · Dr. Ramesh Iyer',
      result:'Cut patient waiting time by 40% in the first month. The appointment reminder alone reduced no-shows from 28% to 6%.',
      metrics:[{n:'40%',l:'Wait time cut'},{n:'28%→6%',l:'No-show rate'},{n:'Month 1',l:'ROI achieved'}], time:'7 working days' },
    { industry:"🏥 Women's Health · Mysuru", hotel:"Sharma Women's Centre", location:'📍 Mysuru, Karnataka · Dr. Priya Sharma',
      result:'WhatsApp prescription delivery is a game changer. Patients actually take the right medicines now. Follow-up rate doubled.',
      metrics:[{n:'2x',l:'Follow-up rate'},{n:'30s',l:'Prescription delivery'},{n:'0',l:'Prescription errors'}], time:'6 working days' },
    { industry:'🏥 General Medicine · Bengaluru', hotel:'Kapoor Multispecialty', location:'📍 Bengaluru, Karnataka · Dr. Arjun Kapoor',
      result:'EMR is so clean and fast. Consultation notes in 2 minutes versus 15 minutes on paper. The ICD-10 autocomplete is brilliant.',
      metrics:[{n:'2 min',l:'Notes per patient'},{n:'87%',l:'Time saved'},{n:'4.9★',l:'Patient rating'}], time:'7 working days' },
  ],
  plans: [
    { id:'starter', name:'Starter', price:19999, users:'1 doctor', rooms:'Small clinic', period:'per year', popular:false,
      description:'For individual clinics & small practices. Everything to go paperless.',
      features:['Patient registration & UHID','Appointment scheduling','Basic EMR & vitals','GST invoice generation','WhatsApp appointment reminder','1 doctor + 2 staff users','AWS hosted — NNC infra'],
      notIncluded:['Prescription module','Lab result management'],
      support:'30 days', response:'24 hrs', mobile:'None' },
    { id:'growth', name:'Growth', price:39999, users:'3 doctors', rooms:'Multi-doctor clinic', period:'per year', popular:true,
      description:'For multi-doctor clinics and hospitals up to 20 beds.',
      features:['Everything in Starter','Full EMR & consultation notes','ICD-10 diagnosis autocomplete','Prescription & drug management','Lab result management','3 doctors + 7 staff users','Patient WhatsApp reports','Advanced analytics','60 days post-launch support'],
      notIncluded:['Multi-branch dashboard'],
      support:'60 days', response:'8 hrs', mobile:'None' },
    { id:'enterprise', name:'Enterprise', price:79999, users:'7 doctors', rooms:'Multi-branch', period:'per year', popular:false,
      description:'For hospital chains & multi-branch clinics. Full compliance and advanced modules.',
      features:['Everything in Growth','Multi-branch dashboard','7 doctors + unlimited staff','HIPAA-aligned audit logs','Custom KPI dashboards','API access','Dedicated account manager','90 days priority support'],
      notIncluded:[],
      support:'90 days', response:'4 hrs', mobile:'None' },
  ],
  problems: [
    { icon:'📋', title:'Patient File Chaos', body:'Paper files, missing records, and duplicate patient profiles. Staff spend 30 minutes searching for records before every consultation.' },
    { icon:'🗓', title:'Appointment No-Shows', body:'No automated reminders mean 20–30% no-show rates every day. That is direct revenue walking out the door every single morning.' },
    { icon:'💊', title:'Manual Prescription Errors', body:'Handwritten prescriptions with illegible drug names. Wrong dosages. No record of what was prescribed at the last visit.' },
    { icon:'🧾', title:'GST Billing Nightmares', body:'Manual billing with wrong HSN codes, missed GST components, and hours wasted preparing monthly tax reports.' },
    { icon:'📊', title:'Zero Analytics', body:'You do not know your busiest doctors, most profitable treatments, or patient retention rate. You are flying completely blind.' },
    { icon:'💬', title:'No Patient Communication', body:'No automated appointment reminders, no follow-up messages, no report delivery. Everything is a manual phone call.' },
  ],
  features: [
    { id:'patients', icon:'👤', title:'Patient Registration & UHID', desc:'Complete patient lifecycle from first visit. Auto-generate UHID, capture full history, insurance details, and emergency contacts.',
      bullets:['UHID auto-generation per patient','Full medical history timeline','Insurance provider & policy tracking','Emergency contact management'] },
    { id:'appointments', icon:'🗓', title:'Appointment Scheduling', desc:'Slot-based scheduling with doctor-wise calendars. Automated WhatsApp reminders 24 hours before. One-click reschedule.',
      bullets:['Doctor-wise slot grid','15-minute slot management','Auto WhatsApp reminder 24hrs prior','No-show tracking & follow-up'] },
    { id:'emr', icon:'📋', title:'Electronic Medical Records', desc:'Vitals, ICD-10 diagnosis, consultation notes, prescription — all linked to every appointment. Encrypted at rest.',
      bullets:['Vitals (BP, temp, weight, SpO2)','ICD-10 diagnosis autocomplete','Doctor notes (AES-256 encrypted)','Follow-up date tracking'] },
    { id:'prescriptions', icon:'💊', title:'Prescription Management', desc:'Drug autocomplete from medicines master. Dosage, frequency, duration. One-click printable PDF. Delivered via WhatsApp.',
      bullets:['Drug name autocomplete','Dosage frequency duration entry','Prescription PDF generation','WhatsApp delivery to patient'] },
    { id:'billing', icon:'🧾', title:'GST Billing & Invoicing', desc:'Auto GST calculation with correct HSN codes for medical services. One-click invoice delivery on WhatsApp.',
      bullets:['CGST + SGST + IGST split','Consultation & lab fee billing','Discount with approval','PDF invoice via WhatsApp'] },
    { id:'analytics', icon:'📊', title:'Analytics Dashboard', desc:'OPD count, revenue by department, doctor performance, patient retention — live on one screen.',
      bullets:['Daily/weekly/monthly OPD','Revenue by doctor & department','Patient return rate','Export to Excel & PDF'] },
  ],
  processSteps: [
    { title:'Pay & Book Slot', text:'Pay via Razorpay. Team confirms your onboarding slot within 2 hours on WhatsApp.' },
    { title:'Discovery Call',  text:'30-min call. We document specialties, staff roles, fee structure, and GST details.' },
    { title:'Setup & Data Migration', text:'Configure CoreOS on AWS, migrate patient records, set WhatsApp templates.' },
    { title:'Go Live + Training', text:'2-hour staff training. 30–90 days post-launch support.' },
  ],
  comparison: [
    { category:'Core Modules', rows:[
      { icon:'👤', feature:'Patient Registration & UHID',    starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🗓', feature:'Appointment Scheduling',         starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'📋', feature:'Basic EMR & Vitals',            starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💊', feature:'Prescription Management',        starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🔬', feature:'Lab Result Management',          starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🏥', feature:'Multi-Branch Dashboard',         starter:'—', growth:'—', enterprise:'✓' },
    ]},
    { category:'Users & Access', rows:[
      { icon:'👨‍⚕️', feature:'Doctor Accounts',    starter:'1',       growth:'3',        enterprise:'7' },
      { icon:'👤',   feature:'Staff Accounts',      starter:'2 users', growth:'7 users',  enterprise:'Unlimited' },
      { icon:'🔑',   feature:'Role-Based Access',   starter:'Basic',   growth:'Advanced', enterprise:'Custom' },
    ]},
    { category:'Automation & Communication', rows:[
      { icon:'📱', feature:'WhatsApp Appointment Reminder',  starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💌', feature:'Invoice Delivery via WhatsApp',  starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🔔', feature:'Auto Follow-up & Review Requests', starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'📲', feature:'Patient Report Sharing (WhatsApp)', starter:'—', growth:'✓', enterprise:'✓' },
    ]},
    { category:'Analytics & Reports', rows:[
      { icon:'📊', feature:'OPD Revenue Dashboard',       starter:'Basic', growth:'Advanced', enterprise:'Custom' },
      { icon:'📈', feature:'Doctor Performance Analytics', starter:'—',     growth:'✓',        enterprise:'✓' },
      { icon:'📤', feature:'Export to Excel & PDF',        starter:'—',     growth:'✓',        enterprise:'✓' },
      { icon:'🎯', feature:'Custom KPI Dashboards',        starter:'—',     growth:'—',        enterprise:'✓' },
    ]},
    { category:'Technology & Compliance', rows:[
      
      { icon:'🔒', feature:'AES-256 Encrypted EMR',    starter:'✓', growth:'✓',       enterprise:'✓' },
      { icon:'📜', feature:'HIPAA-Aligned Audit Logs', starter:'—', growth:'—',       enterprise:'✓' },
    ]},
    { category:'Support & Onboarding', rows: sharedSupportRows },
  ],
  testimonials: [
    { text:'We cut patient waiting time by 40% in the first month. The appointment reminder alone reduced no-shows from 28% to 6%.', initials:'RI', name:'Dr. Ramesh Iyer', role:'Cardiologist · Iyer Heart Clinic, Bengaluru' },
    { text:'WhatsApp prescription delivery is a game changer. Patients actually take the right medicines now. Our follow-up rate doubled.', initials:'PS', name:'Dr. Priya Sharma', role:'Gynaecologist · Sharma Women\'s Centre, Mysuru' },
    { text:'EMR is so clean and fast. I write consultation notes in 2 minutes now versus 15 on paper. ICD-10 autocomplete is brilliant.', initials:'AK', name:'Dr. Arjun Kapoor', role:'GP · Kapoor Multispecialty, Bengaluru' },
  ],
  faqs: [
    { q:'Is patient data safe and HIPAA compliant?', a:'All patient records on AWS Mumbai with AES-256 encryption. Consultation notes encrypted separately. Row-Level Security ensures your patient data is isolated from all other clinics. Full audit logs track every access.' },
    { q:'Can I migrate existing patient records?', a:'Yes — included in all plans. We migrate from Excel, paper records, or your existing HMS software. UHID generation covers all migrated records.' },
    { q:'How does appointment scheduling work?', a:'Doctor-wise slot grid in 15-minute intervals. System auto-sends WhatsApp reminders 24 hours before. No-shows tracked and auto-followed-up.' },
    { q:'Can multiple doctors use the system?', a:'Starter: 1 doctor. Growth: 3 doctors. Enterprise: 7+ doctors. Each doctor has their own schedule, patient list, and prescription history.' },
    { q:'Does it work for diagnostic centres?', a:'Yes. Lab result management, report uploads to S3, and secure patient-facing PDF sharing via WhatsApp included in Growth and Enterprise.' },
    { q:'What about GST billing?', a:'Auto-calculates CGST + SGST with correct HSN codes for medical consultation, lab, and pharmacy services. One-click PDF invoice sent via WhatsApp.' },
  ],
  finalH2: "Your Clinic Deserves Better than Paper Records.",
  finalP:  "Join 300+ clinics and hospitals already running on CoreOS CRM. Setup in 7 days. HIPAA-aligned. AWS hosted.",
}

// ══════════════════════════════════════════════════════════
// REAL ESTATE
// ══════════════════════════════════════════════════════════
export const realestateData: IndustryPageConfig = {
  id: 'realestate',
  metaTitle: "CoreOS Real Estate CRM — Builder & Broker Management Software India | NNC",
  metaDesc:  "Complete real estate CRM for builders and brokers. Lead pipeline, unit inventory, site visits, agreement generation. AWS hosted. From ₹24,999/year.",
  h1:        ["Close More Units.", "Lose Fewer Leads.", "Sell Faster."],
  h1Sub:     "Trusted by 150+ builders & brokers across India",
  heroBadge: "REAL ESTATE CRM — INDIA BUILT · AWS HOSTED",
  heroSub:   "CoreOS Real Estate CRM gives builders and brokers a complete lead-to-closure pipeline — Kanban lead tracking, unit inventory with floor plan, site visit scheduling, and agreement generation. AWS hosted. From ₹24,999/year.",
  urgencyText: "Now serving builders & brokers across Bengaluru, Mysuru, Mumbai & Hyderabad",
  proofText:   "150+ builders & brokers using CoreOS · ★★★★★ 4.8/5",
  sizeLabel:   "Number of Projects",
  wins: [
    { industry:'🏗 Residential · Bengaluru', hotel:'Prestige Properties', location:'📍 Bengaluru · 5 Projects · Growth Plan',
      result:'Converted 3 more units per month within 60 days. The Kanban pipeline made it impossible for agents to forget a follow-up.',
      metrics:[{n:'+3',l:'Units/month'},{n:'60 days',l:'ROI achieved'},{n:'0',l:'Missed follow-ups'}], time:'7 working days' },
    { industry:'🏗 Builder · Mumbai', hotel:'Shah Buildcon', location:'📍 Mumbai · 3 Projects · Growth Plan',
      result:'The unit inventory floor plan is exactly what we needed. No more double-bookings. Clients see which units are available in real time.',
      metrics:[{n:'0',l:'Double bookings'},{n:'100%',l:'Inventory accuracy'},{n:'Real time',l:'Unit visibility'}], time:'7 working days' },
    { industry:'🏗 Developer · Pune', hotel:'Mehta Developers', location:'📍 Pune · 2 Projects · Starter Plan',
      result:'Demand letter automation alone is worth the subscription. We used to chase payments manually. Now they come to us.',
      metrics:[{n:'100%',l:'On-time payments'},{n:'₹0',l:'Late collections'},{n:'Auto',l:'Demand letters'}], time:'5 working days' },
  ],
  plans: [
    { id:'starter', name:'Starter', price:24999, users:'1 agent', rooms:'Up to 2 projects', period:'per year', popular:false,
      description:'For individual brokers & small builders with up to 2 projects.',
      features:['Lead pipeline (Kanban view)','Unit inventory & floor plan','Site visit scheduling','Basic client communication','1 agent + 2 staff users','AWS hosted — NNC infra','Setup & data migration'],
      notIncluded:['Channel partner module','Agreement generation','Advanced analytics'],
      support:'30 days', response:'24 hrs', mobile:'None' },
    { id:'growth', name:'Growth', price:49999, users:'5 agents', rooms:'Up to 5 projects', period:'per year', popular:true,
      description:'For builders with 2–5 projects and broker firms.',
      features:['Everything in Starter','Channel partner management','Agreement & allotment letters','Advanced lead analytics','5 agents + 10 staff users','WhatsApp lead automation','Demand letter & payment tracking','60 days post-launch support'],
      notIncluded:['Multi-project group dashboard'],
      support:'60 days', response:'8 hrs', mobile:'None' },
    { id:'enterprise', name:'Enterprise', price:99999, users:'Unlimited agents', rooms:'Unlimited projects', period:'per year', popular:false,
      description:'For large builders with 5+ projects and multi-city operations.',
      features:['Everything in Growth','Multi-project group dashboard','Unlimited agents & staff','RERA compliance module','Custom reports & dashboards','Dedicated account manager','90 days priority support'],
      notIncluded:[],
      support:'90 days', response:'4 hrs', mobile:'None' },
  ],
  problems: [
    { icon:'🎯', title:'Leads Falling Through Cracks', body:'Enquiries from web, IVR, referrals, and walk-ins with no single pipeline. Without tracking, 40% of leads are never followed up properly.' },
    { icon:'📋', title:'No Unit Inventory Control', body:'Which flats are available, held, or booked? Your team calls each other to find out. Double-bookings happen and clients walk away permanently.' },
    { icon:'🗓', title:'Site Visit No-Shows', body:'No automated reminders. Agents forget. Prospects lose interest. You are losing 3–4 serious buyers every week to poor follow-up.' },
    { icon:'📄', title:'Manual Agreement Writing', body:'Agreements typed in Word with copy-paste errors. Wrong names, wrong unit numbers, wrong payment schedules. Legal exposure every month.' },
    { icon:'💰', title:'No Payment Tracking', body:'You do not know which customers owe money, how much, and since when. Demand letters are sent late. Cash flow suffers every quarter.' },
    { icon:'📊', title:'Zero Sales Visibility', body:'You cannot see agent-wise performance, conversion rates, or lead sources. You are spending on marketing without knowing what works.' },
  ],
  features: [
    { id:'leads', icon:'🎯', title:'Lead Pipeline (Kanban)', desc:'Complete lead-to-closure pipeline with Kanban. Track every lead from first enquiry to booking.',
      bullets:['New → Called → Site Visit → Negotiation → Booked','Round-robin auto-assignment to agents','Hot lead flagging with 2-hour SLA','Stage history log for every lead'] },
    { id:'inventory', icon:'🏠', title:'Unit Inventory & Floor Plan', desc:'Interactive floor plan grid. Colour-coded by status. Hold units with expiry timer. Export to Excel.',
      bullets:['Green=Available, Amber=Hold, Red=Booked, Grey=Sold','48-hour auto-release for held units','Carpet area, super area, PLC pricing','One-click inventory export'] },
    { id:'visits', icon:'📍', title:'Site Visit Management', desc:'Schedule site visits with agent and prospect. Google Calendar sync. Auto WhatsApp reminder.',
      bullets:['Date-time picker with agent calendar','Google Calendar sync','Auto WhatsApp reminder to prospect','Visit feedback & outcome tracking'] },
    { id:'agreements', icon:'📄', title:'Agreement & Documents', desc:'Auto-generate allotment letters, agreements, and demand letters using your templates.',
      bullets:['Agreement auto-generation from templates','Allotment letter PDF','Demand letter with payment schedule','Document versioning & history'] },
    { id:'payments', icon:'💰', title:'Payment Tracking', desc:'Track all payment milestones. Auto-send demand letters. Flag overdue payments.',
      bullets:['Milestone-wise payment tracking','Auto demand letter on due date','Overdue alerts to sales manager','Receipt PDF via WhatsApp'] },
    { id:'analytics', icon:'📊', title:'Sales Analytics', desc:'Agent-wise conversion rates, source-wise lead quality, project-wise booking pace — all live.',
      bullets:['Agent performance leaderboard','Lead source ROI analysis','Project-wise booking velocity','Export to Excel & PDF'] },
  ],
  processSteps: [
    { title:'Pay & Book Slot', text:'Pay via Razorpay. Team confirms within 2 hours.' },
    { title:'Discovery Call',  text:'30-min call. Document projects, unit types, pricing, agents, lead sources.' },
    { title:'Setup & Data Migration', text:'Configure on AWS, migrate existing leads and unit inventory.' },
    { title:'Go Live + Training', text:'Agent training. 30–90 days post-launch support.' },
  ],
  comparison: [
    { category:'Core Modules', rows:[
      { icon:'🎯', feature:'Lead Pipeline (Kanban)',           starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🏠', feature:'Unit Inventory & Floor Plan',      starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'📍', feature:'Site Visit Scheduling',            starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'📄', feature:'Agreement & Allotment Letters',    starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'💰', feature:'Payment Milestone Tracking',       starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🤝', feature:'Channel Partner Management',       starter:'—', growth:'✓', enterprise:'✓' },
    ]},
    { category:'Users & Access', rows:[
      { icon:'👥', feature:'Agent Accounts',        starter:'1 agent',  growth:'5 agents',  enterprise:'Unlimited' },
      { icon:'👤', feature:'Staff User Accounts',   starter:'2 users',  growth:'10 users',  enterprise:'Unlimited' },
      { icon:'🏗', feature:'Multi-Project Dashboard', starter:'—',       growth:'—',         enterprise:'✓' },
    ]},
    { category:'Automation & Communication', rows:[
      { icon:'📱', feature:'WhatsApp Lead Notifications',       starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🔔', feature:'Auto Site Visit Reminders',         starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💌', feature:'Demand Letter Auto-Dispatch',       starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'📲', feature:'Agreement Delivery via WhatsApp',   starter:'—', growth:'✓', enterprise:'✓' },
    ]},
    { category:'Analytics & Reports', rows:[
      { icon:'📊', feature:'Lead Conversion Dashboard',   starter:'Basic',    growth:'Advanced', enterprise:'Custom' },
      { icon:'📈', feature:'Agent Performance Analytics', starter:'—',        growth:'✓',        enterprise:'✓' },
      { icon:'📤', feature:'Export to Excel & PDF',       starter:'—',        growth:'✓',        enterprise:'✓' },
      { icon:'🎯', feature:'Custom KPI Dashboards',       starter:'—',        growth:'—',        enterprise:'✓' },
    ]},
    { category:'Technology', rows:[
      
      { icon:'📅', feature:'Google Calendar Sync',    starter:'—', growth:'✓',       enterprise:'✓' },
      
    ]},
    { category:'Support & Onboarding', rows: sharedSupportRows },
  ],
  testimonials: [
    { text:'We converted 3 more units per month within 60 days. The Kanban pipeline made it impossible for agents to forget a follow-up.', initials:'RK', name:'Rajesh Kumar', role:'Sales Head · Prestige Properties, Bengaluru' },
    { text:'The unit inventory floor plan is exactly what we needed. No more double-bookings. Clients see available units in real time.', initials:'PS', name:'Priya Shah', role:'Director · Shah Buildcon, Mumbai' },
    { text:'Demand letter automation alone is worth the subscription. We used to chase payments manually. Now they come to us.', initials:'AM', name:'Anand Mehta', role:'MD · Mehta Developers, Pune' },
  ],
  faqs: [
    { q:'Is this for builders, brokers, or both?', a:'Both. Builders use it for project inventory, sales pipeline, and payment tracking. Brokers use it for lead management, client communication, and site visit coordination.' },
    { q:'How many projects can I manage?', a:'Starter: 2 projects. Growth: up to 5. Enterprise: unlimited with a consolidated group dashboard across all projects and cities.' },
    { q:'Does it integrate with web lead forms?', a:'Yes. We set up webhooks during onboarding to auto-capture leads from website forms, IVR, and 99acres/MagicBricks enquiry forms directly into the pipeline.' },
    { q:'Can I generate agreements automatically?', a:'Growth and Enterprise plans auto-generate agreements and allotment letters from your templates. System fills buyer details, unit details, and payment schedule automatically.' },
    { q:'What is the channel partner module?', a:'Tracks broker referrals, commission structures, and payment status. Each channel partner gets a login to check their leads and commissions.' },
    { q:'How does payment milestone tracking work?', a:'You define milestones (booking, slab, possession) and amounts. System auto-sends demand letters on due dates. Overdue payments flagged to your sales manager.' },
  ],
  finalH2: "Your Sales Team Deserves Better than WhatsApp Groups.",
  finalP:  "Join 150+ builders and brokers already using CoreOS CRM. Setup in 7 days. Full pipeline visibility from day one.",
}

// ══════════════════════════════════════════════════════════
// EDUCATION
// ══════════════════════════════════════════════════════════
export const educationData: IndustryPageConfig = {
  id: 'education',
  metaTitle: "CoreOS Education CRM — Coaching Institute & Academy Management Software | NNC",
  metaDesc:  "Complete education CRM for coaching institutes, academies and schools. Student enrollment, attendance, fee collection, WhatsApp reminders. From ₹14,999/year.",
  h1:        ["Run Your Institute", "Like a Top 1%", "Academy."],
  h1Sub:     "Trusted by 200+ coaching institutes & academies across India",
  heroBadge: "EDUCATION CRM — INDIA BUILT · AWS HOSTED",
  heroSub:   "CoreOS Education CRM handles student enrollment, batch management, QR-based attendance, fee collection with auto-reminders, and online test results — all in one dashboard. AWS hosted. From ₹14,999/year.",
  urgencyText: "Now serving coaching institutes & academies across Bengaluru, Mysuru, Mumbai & Hyderabad",
  proofText:   "200+ institutes running on CoreOS · ★★★★★ 4.9/5",
  sizeLabel:   "Number of Students",
  wins: [
    { industry:'🎓 Coaching · Bengaluru', hotel:'KSR Academy', location:'📍 Bengaluru · 450 Students · Growth Plan',
      result:'Fee collection went from a monthly nightmare to fully automated. Parents pay before we even call them because the WhatsApp reminder does the job.',
      metrics:[{n:'100%',l:'On-time fees'},{n:'0',l:'Manual reminders'},{n:'Month 1',l:'ROI achieved'}], time:'6 working days' },
    { industry:'🎓 Coaching · Mysuru', hotel:'Shetty Coaching Centre', location:'📍 Mysuru · 280 Students · Starter Plan',
      result:'QR attendance took 5 minutes to set up per student. Now faculty mark attendance in 30 seconds. We got 100% compliance in week one.',
      metrics:[{n:'30s',l:'Attendance marking'},{n:'100%',l:'Compliance week 1'},{n:'5 min',l:'Setup per batch'}], time:'5 working days' },
    { industry:'🎓 Coaching · Bengaluru', hotel:'Toppers Academy', location:'📍 Bengaluru · 600 Students · Growth Plan',
      result:'We give online tests on Saturday, results auto-shared by Sunday morning. Parents love the transparency. Admissions up 35% after testimonials spread.',
      metrics:[{n:'35%',l:'Admissions up'},{n:'Instant',l:'Result sharing'},{n:'4.9★',l:'Parent rating'}], time:'7 working days' },
  ],
  plans: [
    { id:'starter', name:'Starter', price:14999, users:'1 staff', rooms:'Up to 150 students', period:'per year', popular:false,
      description:'For small coaching centres up to 150 students.',
      features:['Student enrollment & ID generation','Batch & course management','QR-code attendance marking','Fee collection & receipts','WhatsApp fee reminder','1 staff user','AWS hosted — NNC infra','Setup & data migration'],
      notIncluded:['Fee defaulter automation','Online test module','Multi-branch'],
      support:'30 days', response:'24 hrs', mobile:'None' },
    { id:'growth', name:'Growth', price:29999, users:'3 staff', rooms:'Up to 500 students', period:'per year', popular:true,
      description:'For institutes with up to 500 students across multiple batches.',
      features:['Everything in Starter','Fee defaulter tracking & auto-reminders','Late fee automation','Parent WhatsApp communication','Online test with auto-grading','3 staff + faculty users','Student ID card with QR','60 days post-launch support'],
      notIncluded:['Multi-branch dashboard'],
      support:'60 days', response:'8 hrs', mobile:'None' },
    { id:'enterprise', name:'Enterprise', price:59999, users:'7 staff', rooms:'500+ students', period:'per year', popular:false,
      description:'For large institutes with 500+ students and multiple branches.',
      features:['Everything in Growth','Multi-branch dashboard','7 staff + unlimited faculty','Certificate generation','Custom KPI dashboards','API access','Dedicated account manager','90 days priority support'],
      notIncluded:[],
      support:'90 days', response:'4 hrs', mobile:'None' },
  ],
  problems: [
    { icon:'📋', title:'Enrollment Paper Trail', body:'Student forms, documents, fee receipts — all in different files and folders. Finding a student record takes 10 minutes of searching every time.' },
    { icon:'💰', title:'Fee Collection Chaos', body:'No system to track who paid, who is partial, and who is overdue. You are chasing parents manually over WhatsApp every month.' },
    { icon:'✅', title:'Attendance on Paper', body:'Manual attendance sheets get lost. You cannot tell which student has dropped below 75% attendance until it is too late to intervene.' },
    { icon:'📱', title:'No Parent Communication', body:'Parents have no visibility into attendance, fee status, or upcoming tests. You get 20 calls a day asking for basic updates.' },
    { icon:'📊', title:'Zero Batch Analytics', body:'You do not know which batch has the highest dropout, which faculty has the best results, or which course is most profitable.' },
    { icon:'📝', title:'Manual Test Evaluation', body:'Paper tests, manual correction, results typed into Excel. It takes 3 days to share marks. Students and parents lose patience.' },
  ],
  features: [
    { id:'enrollment', icon:'👤', title:'Student Enrollment', desc:'Multi-step enrollment — personal info, course selection, fee plan, document upload. Auto-generate Student ID with QR code.',
      bullets:['Auto Student ID (NNC2026001 format)','Document upload (Aadhaar, marksheet)','Fee plan selection at enrollment','Welcome kit via WhatsApp on day 1'] },
    { id:'attendance', icon:'✅', title:'QR-Code Attendance', desc:'Student scans ID card QR on entry. Attendance marked instantly. Low-attendance alerts auto-sent to parents.',
      bullets:['QR scan-based marking','Manual override for faculty','Parent WhatsApp alert below 75%','Monthly attendance report'] },
    { id:'fees', icon:'💰', title:'Fee Collection & Reminders', desc:'Track every installment. Auto WhatsApp reminders 3 days before due. Late fee automation. PDF receipt generation.',
      bullets:['Installment-wise tracking','3-day advance WhatsApp reminder','Late fee per day automation','PDF receipt on payment'] },
    { id:'tests', icon:'📝', title:'Online Test & Auto-Grading', desc:'Create tests with MCQ, upload answer keys. Auto-grade on submission. Result PDF sent to student and parent.',
      bullets:['MCQ test creation','Answer key upload','Auto-grading on submit','Result PDF to WhatsApp'] },
    { id:'analytics', icon:'📊', title:'Batch & Course Analytics', desc:'Batch-wise attendance, fee collection, test performance. Faculty dashboard. Dropout risk alerts.',
      bullets:['Batch attendance heatmap','Fee collection per batch','Test score distribution','Dropout risk flagging'] },
    { id:'certificates', icon:'🎓', title:'Certificate Generation', desc:'Auto-generate course completion certificates with QR code for verification. PDF delivered via WhatsApp.',
      bullets:['Course completion certificate','QR code verification link','Batch-wise bulk generation','Branded template support'] },
  ],
  processSteps: [
    { title:'Pay & Book Slot', text:'Pay via Razorpay. Team confirms within 2 hours.' },
    { title:'Discovery Call',  text:'30-min call. Document courses, batches, fee structures, faculty.' },
    { title:'Setup & Data Migration', text:'Migrate student records, set WhatsApp templates, configure QR attendance.' },
    { title:'Go Live + Training', text:'Staff training. 30–90 days support.' },
  ],
  comparison: [
    { category:'Core Modules', rows:[
      { icon:'👤', feature:'Student Enrollment & ID',        starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'✅', feature:'QR-Code Attendance',             starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💰', feature:'Fee Collection & Receipts',      starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'📝', feature:'Online Test & Auto-Grading',     starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🎓', feature:'Certificate Generation',         starter:'—', growth:'—', enterprise:'✓' },
      { icon:'🏢', feature:'Multi-Branch Dashboard',         starter:'—', growth:'—', enterprise:'✓' },
    ]},
    { category:'Users & Access', rows:[
      { icon:'👥', feature:'Staff User Accounts',    starter:'1 user',     growth:'3 users',     enterprise:'7 users' },
      { icon:'👨‍🏫', feature:'Faculty Accounts',    starter:'1 faculty',  growth:'Unlimited',   enterprise:'Unlimited' },
      { icon:'🔑', feature:'Role-Based Access',       starter:'Basic',      growth:'Advanced',    enterprise:'Custom' },
    ]},
    { category:'Automation & Communication', rows:[
      { icon:'📱', feature:'WhatsApp Fee Reminder',          starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💌', feature:'Fee Receipt via WhatsApp',       starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🔔', feature:'Attendance Alert to Parent',     starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'📲', feature:'Test Result via WhatsApp',       starter:'—', growth:'✓', enterprise:'✓' },
    ]},
    { category:'Analytics & Reports', rows:[
      { icon:'📊', feature:'Batch & Fee Dashboard',         starter:'Basic', growth:'Advanced', enterprise:'Custom' },
      { icon:'📈', feature:'Faculty Performance Analytics', starter:'—',     growth:'✓',        enterprise:'✓' },
      { icon:'📤', feature:'Export to Excel & PDF',         starter:'—',     growth:'✓',        enterprise:'✓' },
      { icon:'🎯', feature:'Custom KPI Dashboards',         starter:'—',     growth:'—',        enterprise:'✓' },
    ]},
    { category:'Technology', rows:[
      
      { icon:'🔌', feature:'API Access',        starter:'—', growth:'—',       enterprise:'✓' },
      
    ]},
    { category:'Support & Onboarding', rows: sharedSupportRows },
  ],
  testimonials: [
    { text:'Fee collection went from a monthly nightmare to fully automated. Parents pay before we even call because the WhatsApp reminder does the job.', initials:'RK', name:'Ravi Kumar', role:'Director · KSR Academy, Bengaluru' },
    { text:'QR attendance took 5 minutes to set up per student. Now faculty mark attendance in 30 seconds. 100% compliance in week one.', initials:'PS', name:'Priya Shetty', role:'Principal · Shetty Coaching, Mysuru' },
    { text:'We give tests on Saturday, results auto-shared by Sunday morning. Parents love the transparency. Admissions up 35%.', initials:'AM', name:'Anand Murthy', role:'MD · Toppers Academy, Bengaluru' },
  ],
  faqs: [
    { q:'How does QR attendance work?', a:'Each student gets a QR code on their ID card. They scan it at the entrance using a tablet or phone. Attendance marked instantly. If below 75%, the system auto-alerts parents via WhatsApp.' },
    { q:'Can I track fee defaulters automatically?', a:'Yes. The system identifies students with overdue installments and auto-sends WhatsApp reminders to student and parent. Late fees applied automatically based on your configured rate per day.' },
    { q:'How many batches can I manage?', a:'No limit on batches in any plan. Unlimited courses, batches, and timetables. Each batch has its own attendance, fee tracking, and test history.' },
    { q:'Can I migrate existing student data?', a:'Yes — included in all plans. We migrate from Excel, Tally, or any existing software. Student IDs, batch assignments, fee history, and attendance records all migrated.' },
    { q:'What is included in the certificate module?', a:'Enterprise plan auto-generates branded course completion certificates. Each certificate has a QR code linking to a verification page. Bulk generation per batch in one click.' },
    { q:'Can I access CoreOS CRM on my phone?', a:'Yes — all plans are fully mobile-responsive. You can access CoreOS CRM from any browser on your phone, tablet, or desktop. No app download required — just open the link and log in.' },
  ],
  finalH2: "Your Institute Deserves Better than Paper Registers.",
  finalP:  "Join 200+ coaching institutes and academies already running on CoreOS CRM. Setup in 7 days. AWS hosted.",
}

// ══════════════════════════════════════════════════════════
// EVENTS
// ══════════════════════════════════════════════════════════
export const eventsData: IndustryPageConfig = {
  id: 'events',
  metaTitle: "CoreOS Events CRM — Wedding & Corporate Event Management Software | NNC",
  metaDesc:  "Complete events CRM for wedding planners and event companies. Enquiry pipeline, task checklists, vendor management, budget tracking. From ₹19,999/year.",
  h1:        ["Execute Flawless Events.", "Every Single Time."],
  h1Sub:     "Trusted by 100+ event companies & wedding planners across India",
  heroBadge: "EVENTS & WEDDING CRM — INDIA BUILT",
  heroSub:   "CoreOS Events CRM gives you complete end-to-end event management — enquiry pipeline, automated task checklists, vendor management, budget vs actual tracking, and client communication. AWS hosted. From ₹19,999/year.",
  urgencyText: "Now serving event companies & wedding planners across Bengaluru, Mysuru, Mumbai & Hyderabad",
  proofText:   "100+ event companies on CoreOS · ★★★★★ 4.9/5",
  sizeLabel:   "Events per Month",
  wins: [
    { industry:'🎪 Events · Bengaluru', hotel:'Khanna Event Co.', location:'📍 Bengaluru · 15 events/month · Growth Plan',
      result:'Stopped having last-minute surprises. The task checklist and Gantt view means every coordinator knows exactly what to do 30 days before the event.',
      metrics:[{n:'0',l:'Last-min surprises'},{n:'100%',l:'Task completion'},{n:'30 days',l:'Advance visibility'}], time:'6 working days' },
    { industry:'🎪 Events · Hyderabad', hotel:'Setty Celebrations', location:'📍 Hyderabad · 12 events/month · Growth Plan',
      result:'Budget tracking changed everything. We went from 12% average overrun to 2% in 3 months. That is pure profit saved per event.',
      metrics:[{n:'12%→2%',l:'Budget overrun'},{n:'₹ saved',l:'Per event'},{n:'3 months',l:'To achieve'}], time:'7 working days' },
    { industry:'🎪 Weddings · Mumbai', hotel:'Dream Weddings', location:'📍 Mumbai · 8 events/month · Enterprise Plan',
      result:'The vendor management module is the best part. I can see in one screen who is confirmed, who is paid, and who needs a call. No more WhatsApp hunting.',
      metrics:[{n:'100%',l:'Vendor visibility'},{n:'0',l:'Missed vendors'},{n:'1 screen',l:'Everything'}], time:'7 working days' },
  ],
  plans: [
    { id:'starter', name:'Starter', price:19999, users:'1 coordinator', rooms:'Up to 10 events/mo', period:'per year', popular:false,
      description:'For small event companies handling up to 10 events per month.',
      features:['Event enquiry pipeline','Task checklist per event','Basic vendor directory','Client communication log','1 coordinator + 2 staff','AWS hosted — NNC infra','Setup & data migration'],
      notIncluded:['Budget vs actual tracking','WhatsApp proposal sending','Multi-coordinator dashboard'],
      support:'30 days', response:'24 hrs', mobile:'None' },
    { id:'growth', name:'Growth', price:39999, users:'3 coordinators', rooms:'Up to 30 events/mo', period:'per year', popular:true,
      description:'For growing event companies with 10–30 events per month.',
      features:['Everything in Starter','Budget vs actual tracker','WhatsApp proposal & invoice','Vendor payment tracking','Gantt task timeline view','3 coordinators + 7 staff','Auto overdue task alerts','60 days post-launch support'],
      notIncluded:['Multi-office dashboard'],
      support:'60 days', response:'8 hrs', mobile:'None' },
    { id:'enterprise', name:'Enterprise', price:79999, users:'Unlimited coordinators', rooms:'Unlimited events', period:'per year', popular:false,
      description:'For large event companies with multiple teams and offices.',
      features:['Everything in Growth','Multi-office dashboard','Unlimited coordinators & staff','Client portal (view-only)','Post-event analytics','API access','Dedicated account manager','90 days priority support'],
      notIncluded:[],
      support:'90 days', response:'4 hrs', mobile:'None' },
  ],
  problems: [
    { icon:'📋', title:'Task Chaos Before Every Event', body:'No master checklist. Different coordinators track tasks differently. Things fall through cracks 2 days before the event. Client calls start.' },
    { icon:'🤝', title:'Vendor Coordination Nightmare', body:'Calling 15 vendors on WhatsApp for confirmations, payments, and delivery times. No single view of who confirmed and who did not.' },
    { icon:'💰', title:'Budget Overruns Every Time', body:'No real-time budget vs actual tracking. You discover you are over budget during the event, not before it. Profit margins get crushed.' },
    { icon:'📄', title:'Manual Proposal Writing', body:'Proposals typed in Word, emailed as PDFs, and clients respond a week later. No tracking of whether they even opened it.' },
    { icon:'🗓', title:'No Task Timeline View', body:'Without a Gantt chart, you cannot see which tasks are due this week, which are overdue, and which coordinator is overloaded.' },
    { icon:'📊', title:'No Post-Event Analytics', body:'After every event you have no data on budget accuracy, vendor performance, or client satisfaction score. Every event starts from scratch.' },
  ],
  features: [
    { id:'pipeline', icon:'🎯', title:'Event Pipeline & Enquiry', desc:'Track every enquiry from first call to signed contract. Automated proposal generation and WhatsApp delivery.',
      bullets:['Enquiry → Proposal → Confirmed → In Progress → Completed','Auto-assign to coordinator','Proposal PDF via WhatsApp','Win/loss analysis by event type'] },
    { id:'tasks', icon:'✅', title:'Task Checklist & Gantt', desc:'Master checklist templates per event type. Gantt timeline view. Overdue task auto-alerts to coordinator.',
      bullets:['Template checklists per event type','Gantt chart with days-to-event','Overdue task auto-flag at 8 AM','Multi-assignee per task'] },
    { id:'vendors', icon:'🤝', title:'Vendor Management', desc:'Full vendor directory with rate cards. Assign vendors to events. Track payment status and delivery confirmations.',
      bullets:['Vendor directory with category & rate card','Event-vendor assignment','Payment status tracking','Vendor rating after event'] },
    { id:'budget', icon:'💰', title:'Budget vs Actual Tracker', desc:'Line-by-line budget vs actual for every cost category. Real-time variance alerts when you exceed budget.',
      bullets:['Category-wise budget entry','Actual expense logging','Variance alert at 80% utilisation','Profitability report per event'] },
    { id:'proposals', icon:'📄', title:'Proposal & Invoice Generation', desc:'Itemised quotation builder. PDF proposal auto-generated. Invoice with GST. Both delivered via WhatsApp.',
      bullets:['Itemised quotation builder','GST-compliant invoice','Advance & balance tracking','WhatsApp / email delivery'] },
    { id:'analytics', icon:'📊', title:'Post-Event Analytics', desc:'Budget accuracy, vendor performance ratings, client NPS — captured and analysed after every event.',
      bullets:['Budget accuracy score','Vendor rating summary','Client satisfaction capture','Year-over-year event growth'] },
  ],
  processSteps: [
    { title:'Pay & Book Slot', text:'Pay via Razorpay. Team confirms within 2 hours.' },
    { title:'Discovery Call',  text:'30-min call. Document event types, team structure, vendor categories, budget model.' },
    { title:'Setup & Data Migration', text:'Configure on AWS, import active events, set up master checklist templates.' },
    { title:'Go Live + Training', text:'Coordinator training. 30–90 days post-launch support.' },
  ],
  comparison: [
    { category:'Core Modules', rows:[
      { icon:'🎯', feature:'Event Enquiry Pipeline',         starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'✅', feature:'Task Checklist per Event',       starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'🤝', feature:'Vendor Directory & Assignment',  starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'💰', feature:'Budget vs Actual Tracker',       starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'📄', feature:'Proposal & GST Invoice',         starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'📊', feature:'Post-Event Analytics',           starter:'—', growth:'—', enterprise:'✓' },
    ]},
    { category:'Users & Access', rows:[
      { icon:'👥', feature:'Coordinator Accounts',   starter:'1',       growth:'3',         enterprise:'Unlimited' },
      { icon:'👤', feature:'Staff User Accounts',    starter:'2 users', growth:'7 users',   enterprise:'Unlimited' },
      { icon:'🏢', feature:'Multi-Office Dashboard', starter:'—',       growth:'—',         enterprise:'✓' },
    ]},
    { category:'Automation & Communication', rows:[
      { icon:'📱', feature:'WhatsApp Proposal Delivery',   starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'💌', feature:'GST Invoice via WhatsApp',     starter:'—', growth:'✓', enterprise:'✓' },
      { icon:'🔔', feature:'Overdue Task Auto-Alert',      starter:'✓', growth:'✓', enterprise:'✓' },
      { icon:'📲', feature:'Client Portal (View-Only)',    starter:'—', growth:'—', enterprise:'✓' },
    ]},
    { category:'Analytics & Reports', rows:[
      { icon:'📊', feature:'Event Pipeline Dashboard',       starter:'Basic', growth:'Advanced', enterprise:'Custom' },
      { icon:'📈', feature:'Vendor Performance Analytics',  starter:'—',     growth:'✓',        enterprise:'✓' },
      { icon:'📤', feature:'Export to Excel & PDF',         starter:'—',     growth:'✓',        enterprise:'✓' },
      { icon:'🎯', feature:'Custom KPI Dashboards',         starter:'—',     growth:'—',        enterprise:'✓' },
    ]},
    { category:'Technology', rows:[
      
      { icon:'🔌', feature:'API Access',        starter:'—', growth:'—',       enterprise:'✓' },
      
    ]},
    { category:'Support & Onboarding', rows: sharedSupportRows },
  ],
  testimonials: [
    { text:'We stopped having last-minute surprises. The task checklist and Gantt view means every coordinator knows exactly what to do 30 days before the event.', initials:'RK', name:'Rahul Khanna', role:'Founder · Khanna Event Co., Bengaluru' },
    { text:'Budget tracking changed everything. We went from 12% average overrun to 2% in 3 months. That is pure profit saved per event.', initials:'PS', name:'Priya Setty', role:'Director · Setty Celebrations, Hyderabad' },
    { text:'The vendor management module is the best part. One screen — who is confirmed, who is paid, who needs a call. No more WhatsApp hunting.', initials:'AM', name:'Anita Mishra', role:'CEO · Dream Weddings, Mumbai' },
  ],
  faqs: [
    { q:'How do task checklists work?', a:'You create master checklist templates per event type (wedding, corporate, birthday). When confirmed, the checklist auto-populates with tasks, deadlines relative to event date, and default assignees. Overdue tasks flagged every morning.' },
    { q:'Can I track vendor payments?', a:'Yes. Each vendor assigned to an event has a payment record. Log advances, balance payments, and due dates. System flags overdue vendor payments and calculates total vendor cost per event.' },
    { q:'How does budget vs actual work?', a:'Enter estimated budget per category (venue, decor, catering, AV) when event confirmed. As you log actual expenses, system shows variance in real time and alerts you at 80% utilisation.' },
    { q:'Can I send proposals from the system?', a:'Growth and Enterprise plans include an itemised quotation builder. Add line items (venue, decor, catering, photography, AV) and system generates branded PDF proposal. Delivered via WhatsApp or email in one click.' },
    { q:'How many events can I manage simultaneously?', a:'No limit on active events in any plan. Dashboard shows all upcoming events sorted by date with task completion status, budget status, and coordinator assignment.' },
    { q:'Is there a client-facing portal?', a:'Enterprise plan includes a read-only client portal where clients can view task progress, vendor status, and budget summary. They cannot make changes — only view.' },
  ],
  finalH2: "Your Events Deserve Better than WhatsApp Groups.",
  finalP:  "Join 100+ event companies and wedding planners already running on CoreOS CRM. Setup in 7 days. AWS hosted.",
}

export const allIndustryData: Record<string, IndustryPageConfig> = {
  hospitality: hospitalityData,
  healthcare:  healthcareData,
  realestate:  realestateData,
  education:   educationData,
  events:      eventsData,
}
